[package]
name = "warustify"
version = "0.0.1"
edition = "2021"

[dependencies]
sysinfo = "0.29" 
notify-rust = "4" 
zbus = "3"      
log = "0.4"      
env_logger = "0.10" 
tokio = { version = "1", features = ["full"] } 
