name: Build and Release
on:
  push:
    branches: [ "main" ]
    tags: [ "v0.0.1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Create Release branch and Tag
    runs-on: ubuntu-latest
    outputs:
      tag: "v${{ steps.vars.outputs.pkg_version }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --release
      - name: Get package version
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=pkg_version::$(node -e "console.log(require('./package.json').version);")"
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.2.0
        with:
          add: "dist"
          force: true
          message: "Built ${{ steps.vars.outputs.sha_short }}"
          ref: "release/v${{ steps.vars.outputs.pkg_version }}"
          tag: "v${{ steps.vars.outputs.pkg_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by Github Actions
      - name: Prepare Release Files
        run: |
          mkdir -p dist
          cp target/release/warustify dist/
          cd dist
          sha256sum warustify > sha256sum.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-assets
          path: dist/

      - name: Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*
          update: true  # 允许覆盖已存在的 Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
